# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build
on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
defaults:
  run:
    shell: bash
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_NOLOGO: true
jobs:
  build:
      strategy:
        fail-fast: false
        matrix:
          os:
            - macos-13
            - macos-14
            - ubuntu-20.04
            - ubuntu-22.04
            - ubuntu-24.04
            - windows-2019
            - windows-2022
      runs-on: ${{ matrix.os }}
      steps:
        - name: Clone repository
          uses: actions/checkout@v4.1.7
          with:
            fetch-depth: 0
            submodules: recursive
        - name: Set up .NET
          uses: actions/setup-dotnet@v4.0.1
        - name: Run Cake
          run: |
            ./cake
        - name: Upload artifacts
          if: always()
          uses: actions/upload-artifact@v4.3.6
          with:
            name: ${{ github.workflow }}-${{ github.run_number }}-${{ github.run_attempt }}-${{ matrix.os }}
            path: |
              out/log
              out/pkg
