# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release
on:
    release:
        types:
            - published
permissions:
    contents: read
defaults:
    run:
        shell: bash
env:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_GENERATE_ASPNET_CERTIFICATE: false
    DOTNET_NOLOGO: true
    NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
jobs:
    release:
        if: github.repository == 'vezel-dev/zig-toolsets'
        runs-on: ubuntu-22.04
        steps:
            - name: Clone repository
              uses: actions/checkout@v4.1.4
              with:
                  fetch-depth: 0
                  submodules: recursive
            - name: Set up .NET
              uses: actions/setup-dotnet@v4.0.0
            - name: Run Cake
              run: |
                  ./cake upload
            - name: Upload artifacts
              if: always()
              uses: actions/upload-artifact@v4.3.3
              with:
                  name: ${{ github.workflow }}-${{ github.run_number }}-${{ github.run_attempt }}
                  path: |
                      out/log
                      out/pkg
