# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release
on:
    release:
        types:
            - published
defaults:
    run:
        shell: bash
env:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_GENERATE_ASPNET_CERTIFICATE: false
    DOTNET_NOLOGO: true
jobs:
    release:
        if: github.repository == 'alexrp/zig-msbuild-toolsets'
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v2.3.4
              with:
                  fetch-depth: 0
                  submodules: recursive
            - name: Extract .NET version
              id: dotnet
              run: |
                  echo ::set-output name=version::$(jq .sdk.version global.json -r)
            - name: Set up .NET
              uses: actions/setup-dotnet@v1.8.0
              with:
                  dotnet-version: ${{ steps.dotnet.outputs.version }}
            - name: Restore project
              run: |
                  dotnet restore
            - name: Build project
              run: |
                  dotnet build --no-restore
            - name: Upload NuGet packages
              run: |
                  dotnet nuget push pkg/*.nupkg -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
